//--------------------------------------------------------------------------------------------------
// Generated using GreenHouse Modeling Library v 1.1
// Please do not edit this file as it will be overwritten the next time the application flow is
// regenerated.
//--------------------------------------------------------------------------------------------------
import QtQuick 2.0
import GreenHouse.Theming 1.0

GreenHouseTheme {
    id: root
    themeBaseDir: "qrc:/Themes/ValidationFlow/AltTheme"
}
